add_newline = false
format = """
$directory\
[](fg:#26233a bg:#403d52)\
$git_branch\
$git_status\
[](fg:#403d52 bg:#1f1d2e)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#1f1d2e bg:#21202e)\
$time\
[ ](fg:#21202e)\
\n$character"""

[directory]
style = "fg:#e0def4 bg:#26233a"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#403d52"
format = '[[ $symbol $branch ](fg:#c4a7e7 bg:#403d52)]($style)'

[git_status]
style = "bg:#403d52"
format = '[[($all_status$ahead_behind )](fg:#c4a7e7 bg:#403d52)]($style)'

[nodejs]
symbol = ""
style = "bg:#1f1d2e"
format = '[[ $symbol ($version) ](fg:#9ccfd8 bg:#1f1d2e)]($style)'

[rust]
symbol = ""
style = "bg:#1f1d2e"
format = '[[ $symbol ($version) ](fg:#9ccfd8 bg:#1f1d2e)]($style)'

[golang]
symbol = ""
style = "bg:#1f1d2e"
format = '[[ $symbol ($version) ](fg:#9ccfd8 bg:#1f1d2e)]($style)'

[php]
symbol = ""
style = "bg:#1f1d2e"
format = '[[ $symbol ($version) ](fg:#9ccfd8 bg:#1f1d2e)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#21202e"
format = '[[  $time ](fg:#908caa bg:#21202e)]($style)'
