# See: https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
gui:
  tabWidth: 2
  useHunkModeInStagingView: false
  showNumstatInFilesView: false
  nerdFontsVersion: "3"
  showFileIcons: true

  theme:
    activeBorderColor:
      - "#f6c177"
      - bold
    inactiveBorderColor:
      - "#6e6a86"
    searchingActiveBorderColor:
      - "#9ccfd8"
      - bold
    optionsTextColor:
      - "#c4a7e7"
    selectedLineBgColor:
      - "#26233a"
    inactiveViewSelectedLineBgColor:
      - "#1f1d2e"
    cherryPickedCommitFgColor:
      - "#9ccfd8"
    cherryPickedCommitBgColor:
      - "#403d52"
    markedBaseCommitFgColor:
      - "#31748f"
    markedBaseCommitBgColor:
      - "#f6c177"
    unstagedChangesColor:
      - "#eb6f92"
    defaultFgColor:
      - "#e0def4"

os:
  editPreset: "nvim"

confirmOnQuit: true
quitOnTopLevelReturn: false
# See https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Command_Keybindings.md
customCommands: []
