# See: https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
gui:
  tabWidth: 2
  useHunkModeInStagingView: false
  showNumstatInFilesView: false
  nerdFontsVersion: "3"
  showFileIcons: true

  theme:
    activeBorderColor:
      - "#ff9e64"
      - bold
    inactiveBorderColor:
      - "#27a1b9"
    searchingActiveBorderColor:
      - "#7dcfff"
      - bold
    optionsTextColor:
      - "#7aa2f7"
    selectedLineBgColor:
      - "#292e42"
    inactiveViewSelectedLineBgColor:
      - "#1f2335"
    cherryPickedCommitFgColor:
      - "#7dcfff"
    cherryPickedCommitBgColor:
      - "#414868"
    markedBaseCommitFgColor:
      - "#7aa2f7"
    markedBaseCommitBgColor:
      - "#e0af68"
    unstagedChangesColor:
      - "#db4b4b"
    defaultFgColor:
      - "#c0caf5"

os:
  editPreset: "nvim"

confirmOnQuit: true
quitOnTopLevelReturn: false
# See https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Command_Keybindings.md
customCommands: []
