gui:
  theme:
    activeBorderColor:
      - "#f6c177"
      - bold
    inactiveBorderColor:
      - "#6e6a86"
    selectedLineBgColor:
      - "#26233a"
    optionsTextColor:
      - "#c4a7e7"
logs:
  timestamps: true
stats:
  graphs:
    - caption: CPU (%)
      statPath: DerivedStats.CPUPercentage
      color: "#31748f"
    - caption: Memory (%)
      statPath: DerivedStats.MemoryPercentage
      color: "#9ccfd8"
